### ISSUE TITLE
Module API improvements

### ISSUE THREAD

**Issue by aklinker1** [wxt-dev/wxt#717]
After writing the first module, a couple of take-aways:

###### Todo:

- [ ] new helper: `isPackageInstalled` - Could be useful to automatically setup unimport presets when the related packages are already installed.
   > See https://github.com/wxt-dev/wxt/pull/720 as an example

###### Completed:

- [x] ~~_second arg `options` should be optional_~~ https://github.com/wxt-dev/wxt/pull/719
- [x] ~~_new helper: `addImportPreset`_~~ https://github.com/wxt-dev/wxt/pull/720
- [x] ~~_Export `WxtModule` type from 'wxt/modules' to avoid "TS2742: The inferred type of 'default' cannot be named without a reference to '../node_modules/wxt/dist/index-q2ZwJBs6'. This is likely not portable. A type annotation is necessary."_~~ https://github.com/wxt-dev/wxt/pull/721
- [x] ~~_type augmentation to add the option types does not work without an import to the module's package_~~ https://github.com/wxt-dev/wxt/pull/722

_Originally posted by @aklinker1 in https://github.com/wxt-dev/wxt/issues/716#issuecomment-2164425167_

**Comment by aklinker1** [comment]
For the last problem, fixing module augmentation, I just need to include a reference to all installed modules in the `.wxt/wxt.d.ts` file.

```diff
// Generated by wxt
/// <reference types="wxt/vite-builder-env" />
/// <reference types="./types/imports.d.ts" />
/// <reference types="./types/paths.d.ts" />
/// <reference types="./types/i18n.d.ts" />
/// <reference types="./types/globals.d.ts" />
+/// <reference types="@wxt-dev/module-vue" />
```

That will cause the module to be included in the project, and for TS to process the module augmentation.

**Comment by aklinker1** [comment]
Released all fixes except for `isPackageInstalled` in [`v0.18.6`](https://github.com/wxt-dev/wxt/releases/tag/wxt-v0.18.6)

**Comment by aklinker1** [comment]
I'm gonna go ahead and close this, I don't think the `isPackageInstalled` helper function is necessary right now. But if someone sees this and whats to add it, feel free to open a PR.
