### ISSUE TITLE
Roadmap to v1.0

### ISSUE THREAD

**Issue by aklinker1** [wxt-dev/wxt#920]
> [!IMPORTANT]
> Please refer to the [v1.0 milestone](https://github.com/wxt-dev/wxt/milestone/2) for the official list of issues that have been created and that need resolved. This milestone includes bugs and small improvements not listed on this issue.

Hello everyone, we're getting super close to WXT v1.0 and I want to share a public roadmap for how we'll get there. Below are the high-level features I want to implement before v1.0 is released.

> 🚧 indicates a potentially breaking change

### v0.X.Y

- [x] File system based manifest generation
- [x] Frontend Framework support
- [ ] Module System 
   - [x] Initial implementation ([#672](https://github.com/wxt-dev/wxt/pull/672))
   - [ ] Runtime Configuration (`app.config.ts` file)
      - [x] Basic implementation ([#792](https://github.com/wxt-dev/wxt/pull/792))
      - [ ] Env var integration
   - [ ] In-depth examples
      - [x] Vue ([#716](https://github.com/wxt-dev/wxt/pull/716))
      - [x] Svelte ([#726](https://github.com/wxt-dev/wxt/pull/726))
      - [x] React ([#729](https://github.com/wxt-dev/wxt/pull/672))
      - [x] Solid ([#730](https://github.com/wxt-dev/wxt/pull/730))
      - [x] Auto-icons ([#851](https://github.com/wxt-dev/wxt/pull/851))
      - [ ] Analytics ([#790](https://github.com/wxt-dev/wxt/pull/790))
   - [ ] Docs
- [ ] 🚧 Don't use `webextension-polyfill` by default ([#868](https://github.com/wxt-dev/wxt/pull/868))
   - [ ] 🚧 Improved `manifest` config typing
   - [ ] 🚧 Named exports for `chrome` namespace types
- [ ] Load config files as ESM ([#297](https://github.com/wxt-dev/wxt/issues/297))
- [ ] Extract `wxt/storage` into it's own NPM package

### v1.0.0-rcX

No alpha/beta, we're going straight into release candidates. Here, we're focusing on bugs and performance. At this point, there will be no more breaking changes and there might only be small features added.

**Comment by mrshappy0** [comment]
@aklinker1 After spending a day attempting to get the `@wxt-dev/analytics` to work with either umami or GA4, I'm wondering if this feature is still in-progress. By the way, great work on this push to v1.0. Loving the progress so far.

**Comment by juliomuhlbauer** [comment]
Why not wxt becomes a Vite Plugin?
https://github.com/wxt-dev/wxt/discussions/1894

**Comment by Arktomson** [comment]
Is it still being iterated and updated?

**Comment by aklinker1** [comment]
> Is it still being iterated and updated?

@Arktomson Yes. WXT has gotten so popular that my time is mostly spent answering people's questions and fixing bugs, not adding new features. Plus I have less time to work on it due to my real job changing. So things have slowed down, and I'm stuck at the 90% complete mark lol

Refer to the milestone for a list of all issues that need to be completed.

**Comment by Arktomson** [comment]
> > Is it still being iterated and updated?
> 
> [@Arktomson](https://github.com/Arktomson) Yes. WXT has gotten so popular that my time is mostly spent answering people's questions and fixing bugs, not adding new features. Plus I have less time to work on it due to my real job changing. So things have slowed down, and I'm stuck at the 90% complete mark lol
> 
> Refer to the milestone for a list of all issues that need to be completed.

It's really great that maintenance is still continuing, and I hope I can participate in the maintenance and development of new features in the future.

**Comment by aklinker1** [comment]
If you're interested in becoming a maintainer and helping out, send me an email! I am very happy to add new maintainers to the project to help out.

https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md#become-a-maintainer

**Comment by Arktomson** [comment]
> If you're interested in becoming a maintainer and helping out, send me an email! I am very happy to add new maintainers to the project to help out.
> 
> https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md#become-a-maintainer

Okay, I need to first familiarize myself with the entire repository, then try to resolve some issues, and afterward submit a maintainer application to you.

**Comment by aklinker1** [comment]
Checkout the "Contribution welcome" issues! Would love for anyone to pick any of them up.

https://github.com/wxt-dev/wxt/issues?q=is%3Aissue%20state%3Aopen%20label%3A%22contribution%20welcome%22

Some already have PRs... Reviewing them would help me out a ton as well.
